// react/src/loader-component.js
export class Loader extends React.Component {
    render() {
        return (
            <div className={this.props.isLoading ? "" : "hidden" + " row"}>
                <div className="col-md-2 col-md-offset-5 well well-lg bg-info">
                    <span className="glyphicon glyphicon-refresh"></span>
                    Loading...
                </div>
            </div>           
        );
    }
}

// angular2/app/loader/loader.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'my-loader',
  template: 
  `
  <div class="row">
      <div class="col-md-2 col-md-offset-5 well well-lg bg-info">
          <span class="glyphicon glyphicon-refresh"></span>
          Loading...
      </div>
  </div>  
  `
})
export class LoaderComponent { }
